pr: 
  branches:
    include:
      - main
trigger: 
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
- group: ovh-registry-secrets
- name: imageName
  value: frontend-prod
- name: registry
  value: u4c2j2w9.c1.gra9.container-registry.ovh.net/corp-web
- name: imageTag
  value: main-$(Build.BuildId)
- name: namespace
  value: corp-web

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Docker Build
    steps:
    - checkout: self

   # 1️ Build & Push Image
    - task: Docker@2
      displayName: Build & Push Frontend
      inputs:
        containerRegistry: OVH -Registry
        repository: corp-web/frontend-prod
        command: buildAndPush
        Dockerfile: Dockerfile
        tags: |
          $(imageTag)

    # 2️ Install Trivy
    - script: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
        trivy --version
      displayName: Install Trivy.

    # 3️ Trivy Image Scan (FAILS BUILD on High/Critical)
    - script: |
        trivy image \
          --exit-code 1 \
          --severity HIGH,CRITICAL \
          --no-progress \
          $(registry)/$(imageName):$(imageTag)
      displayName: Trivy Image Scan.


- stage: Deploy
  displayName: Deploy to OVH Kubernetes
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: Kubernetes Deploy
    steps:
  # 1️ Deploy new image
    - task: KubernetesManifest@1
      displayName: Deploy Frontend
      inputs:
        action: deploy
        kubernetesServiceConnection: OVH-Test-Kubeconfig
        namespace: $(namespace)
        manifests: |
          k8s/overlays/testing/deployment.yaml
        containers: |
          $(registry)/$(imageName):$(imageTag)

  # 2️ Verify rollout (FAILS job if rollout fails)
    - task: Kubernetes@1
      displayName: Verify Rollout
      inputs:
        connectionType: Kubernetes service connection
        kubernetesServiceEndpoint: OVH-Test-Kubeconfig
        namespace: $(namespace)
        command: rollout
        arguments: status deployment/corp-web-frontend --timeout=120s

  # 3️ Rollback on failure
    - task: Kubernetes@1
      displayName: Rollback Deployment
      condition: failed()
      inputs:
        connectionType: Kubernetes service connection
        kubernetesServiceEndpoint: OVH-Test-Kubeconfig
        namespace: $(namespace)
        command: rollout
        arguments: undo deployment/corp-web-frontend

  # 4️ Explicit failure marker (optional but clear)
    - script: |
        echo "Deployment failed. Rollback was executed."
        exit 1
      condition: failed()
      displayName: Mark Deployment as Failed
