# Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corp-web-frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: registrycred
      containers:
      - name: frontend
        image: u4c2j2w9.c1.gra9.container-registry.ovh.net/corp-web/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: frontend-config
          - secretRef:
              name: frontend-secret                                                                    
      #imagePullSecrets:
      #- name: registrycred  # Make sure the secret is created as mentioned before

---
    
