# trigger:
#   branches:
#     include:
#       - Develop  # Trigger the pipeline on updates to the 'develop' branch

# ✅ Use pipeline run button (manual UI or API)
pr: none
trigger: none  # 🔒 Explicitly disables automatic CI triggers

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based agent for the pipeline.

variables:
- group: 'ovh-registry-secrets'
- name: imageName
  value: 'frontend'  # Define the image name
- name: registry
  value: 'u4c2j2w9.c1.gra9.container-registry.ovh.net/kf'  # OVH Container Registry URL
- name: imageTag
  value: 'staging-$(Build.BuildId)'  # Use the build ID as the image tag
- name: 'VITE_AZURE_REDIRECT_URI'
  value: 'http://localhost:3000/dashboard'
- name: 'VITE_AZURE_POST_LOGOUT_REDIRECT_URI'
  value: 'http//localhost:3000/'
- name: 'VITE_AZURE_SUBDOMAIN'
  value: 'dqproj' 
- name: 'VITE_AZURE_SCOPES'
  value: 'openid profile offline_access'
- name: 'VITE_IDENTITY_HOST'
  value: 'dqproj.ciamlogin.com'
- name: 'VITE_MSAL_ENABLE_GRAPH_FALLBACK'
  value: 'true'
- name: 'VITE_KNOWLEDGEHUB_GRAPHQL_URL'
  value: 'http://localhost:4000/graphql'
- name: 'VITE_SUPABASE_URL'
  value: 'https://swwghoukwlnocpfkuluv.supabase.co'
- name: 'AZURE_STORAGE_ACCOUNT'
  value: 'kfmediaitems'
- name: 'AZURE_STORAGE_CONTAINER'
  value: 'mediaitems'
- name: 'VITE_AZURE_CLIENT_ID'
  value: $(AZURE_CLIENT_ID)
- name: 'VITE_SUPABASE_ANON_KEY'
  value: $(SUPABASE_ANON_KEY)
- name: 'AZURE_STORAGE_CONNECTION_STRING'
  value: $(STORAGE_CONNECTION_STRING)


steps:
# 1. Building Vendure Image
- task: Docker@2
  inputs:
    containerRegistry: 'OVH -Registry'
    repository: 'kf/frontend'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    Arguments: |
      --build-arg VITE_AZURE_REDIRECT_URI=$(VITE_AZURE_REDIRECT_URI)
      --build-arg VITE_AZURE_POST_LOGOUT_REDIRECT_URI=$(VITE_AZURE_POST_LOGOUT_REDIRECT_URI)
      --build-arg VITE_AZURE_SUBDOMAIN=$(VITE_AZURE_SUBDOMAIN)
      --build-arg VITE_AZURE_SCOPES=$(VITE_AZURE_SCOPES)
      --build-arg VITE_IDENTITY_HOST=$(VITE_IDENTITY_HOST)
      --build-arg VITE_MSAL_ENABLE_GRAPH_FALLBACK=$(VITE_MSAL_ENABLE_GRAPH_FALLBACK)
      --build-arg VITE_KNOWLEDGEHUB_GRAPHQL_URL=$(VITE_KNOWLEDGEHUB_GRAPHQL_URL)
      --build-arg VITE_SUPABASE_URL=$(VITE_SUPABASE_URL)
      --build-arg AZURE_STORAGE_ACCOUNT=$(AZURE_STORAGE_ACCOUNT)
      --build-arg AZURE_STORAGE_CONTAINER=$(AZURE_STORAGE_CONTAINER)
      --build-arg VITE_AZURE_CLIENT_ID=$(VITE_AZURE_CLIENT_ID)
      --build-arg SUPABASE_ANON_KEY=$(SUPABASE_ANON_KEY)
      --build-arg AZURE_STORAGE_CONNECTION_STRING=$(AZURE_STORAGE_CONNECTION_STRING)

- task: Docker@2
  inputs:
    containerRegistry: 'OVH -Registry'
    repository: 'kf/frontend'
    command: 'push'


# 2. Setting Image with Build Id and creating secret.
- script: |
    echo "Injecting image tag: staging-$(Build.BuildId)"
    sed -i "s|image: .*$|image: $(registry)/$(imageName):$(imageTag)|" k8s/overlays/staging/deployment.yaml
  displayName: 'Setting Image with BuildId'

# 3. Download the Kubeconfig File from Azure DevOps Secure Files
- task: DownloadSecureFile@1
  displayName: 'GetKubeconfig'
  name: GetKubeconfig
  inputs:
    secureFile: 'kubeconfig-kf.yml'  # Use the name of your Kubeconfig secure file in Azure DevOps
  
#4. Authenticating Kubernetes.'
- script: |
      echo "Authenticating Kubernetes"
      mkdir -p ~/.kube
      cp $KUBECONFIG_FILE ~/.kube/config 
      kubectl config use-context kubernetes-admin@khalifa-fund-cluster
      kubectl config get-contexts

  env:
    KUBECONFIG_FILE: $(GetKubeconfig.secureFilePath)
  displayName: 'Authenticating Kubernetes'

# 5. Deploying Image to OVH
- task: Kubernetes@1
  displayName: 'Deploy to OVH Kubernetes Cluster'
  inputs:
    connectionType: 'Kubernetes service connection'
    kubernetesServiceEndpoint: 'Kubernetes-kf'  # Use your secure file path or environment variable
    command: 'apply'
    arguments: '-f k8s/overlays/staging/deployment.yaml'
    # Optional: Add namespace if needed (default or specify another)
    namespace: 'staging'
