apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_AZURE_SUBDOMAIN: "dqproj"
  VITE_AZURE_OPENAI_ENDPOINT: "https://samwe-m4r3zeki-swedencentral.openai.azure.com"
  VITE_AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4-32k"
  VITE_AZURE_OPENAI_API_VERSION: "2024-02-15-preview"
  
