apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
stringData:
  VITE_AZURE_OPENAI_API_KEY: "BaILIpDCFlyXTXXWXQWw5Kxpj6cwpJ4fkTNhJbY2Kj9QmpH4a83VJQQJ99ALACfhMk5XJ3w3AAAAACOGOmml"
  VITE_AIRTABLE_API_KEY: "patg6nLHQqcwzVSwg.643fee130b351e56eeb6894738bfe7a6094c78affc0e031bcdd146a26382ec34"
  VITE_AIRTABLE_BASE_ID: "appOyDiwpGG2FfdAY"
  VITE_AIRTABLE_TABLE_ID: "tbltoHQxFLbzVnBkb"
  VITE_AIRTABLE_CONSULTATION_TABLE_ID: "tblGlhFMGjMGGgl3J"
  VITE_AIRTABLE_WAITLIST_TABLE_ID: "tblZLSx4DlLVz3gLg"
  VITE_AIRTABLE_NEWSLETTER_TABLE_ID: "tblYGnHoSA9urYS5W"
